// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBftIG4PXpZAptLlVvKut9SAY2bcXVO6tw',
    appId: '1:68435394225:web:0c144df859dc7c5bf66c90',
    messagingSenderId: '68435394225',
    projectId: 'inventify-61fe1',
    authDomain: 'inventify-61fe1.firebaseapp.com',
    storageBucket: 'inventify-61fe1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0rl302CQKRBD_dfeodoxeAdDiL4W9iL0',
    appId: '1:68435394225:android:7dd48b0cbdb83064f66c90',
    messagingSenderId: '68435394225',
    projectId: 'inventify-61fe1',
    storageBucket: 'inventify-61fe1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmatSCqCeB7nLTKdGXVwR4LznkCe0iC1c',
    appId: '1:68435394225:ios:ab4942c54bc255acf66c90',
    messagingSenderId: '68435394225',
    projectId: 'inventify-61fe1',
    storageBucket: 'inventify-61fe1.firebasestorage.app',
    iosBundleId: 'com.example.inventify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmatSCqCeB7nLTKdGXVwR4LznkCe0iC1c',
    appId: '1:68435394225:ios:ab4942c54bc255acf66c90',
    messagingSenderId: '68435394225',
    projectId: 'inventify-61fe1',
    storageBucket: 'inventify-61fe1.firebasestorage.app',
    iosBundleId: 'com.example.inventify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBftIG4PXpZAptLlVvKut9SAY2bcXVO6tw',
    appId: '1:68435394225:web:43e6fb79a3880090f66c90',
    messagingSenderId: '68435394225',
    projectId: 'inventify-61fe1',
    authDomain: 'inventify-61fe1.firebaseapp.com',
    storageBucket: 'inventify-61fe1.firebasestorage.app',
  );

}